version: '{build}'
branches:
  only:
  - master
image: macOS
test: off
build_script:
- sh: >-
    dotnet tool update --global Cake.Tool &&
    dotnet build boots.sln &&
    dotnet pack boots.sln &&
    cd Cake.Boots &&
    dotnet cake --target=Mono &&
    dotnet cake
