version: '{build}'
image: macOS
test: off
build_script:
- sh: >-
    curl -L https://dot.net/v1/dotnet-install.sh > dotnet-install.sh &&
    sh dotnet-install.sh --version 5.0.101 --verbose &&
    msbuild boots.sln /restore /t:Build,Pack &&
    ./Cake.Boots/build.sh -t Mono &&
    ./Cake.Boots/build.sh
