version: '{build}'
branches:
  only:
  - main
  - /.+appveyor.+/
image: macOS
test: false
environment:
  Configuration: Release
  Verbosity: Diagnostic
build_script:
- sh: >-
    export PATH="$PATH:~/.dotnet/tools" &&
    dotnet tool update --global Cake.Tool &&
    dotnet build Cake.Boots/Cake.Boots.csproj &&
    cd Cake.Boots &&
    dotnet cake --target=Mono --verbosity=$Verbosity &&
    dotnet cake --verbosity=$Verbosity
