parameters:
  platform: ''

steps:

  - task: MSBuild@1
    displayName: build
    inputs:
      solution: boots.sln
      msbuildArguments: '/restore /t:Build,Pack /p:Configuration=$(Configuration)'

  - task: PublishPipelineArtifact@0
    displayName: artifacts
    inputs:
      artifactName: ${{ parameters.platform }}
      targetPath: bin
    condition: succeededOrFailed()
